### ISSUE TITLE
解説が長いときに自動で改行されず右にはみ出る

### ISSUE THREAD

**Issue by universato** [universato/BrainDriller#23]
問題文でも同様のことが起きるかもしれない

**Comment by universato** [comment]
```css
body {
  white-space: nowrap;
}
```
ヘッダーで日本語が縦になる問題で、これをbody全体に適用させてたことが原因の模様。
折り返したい方に`white-spade: normal;`を指定する方法もあるが、これは打ち消すようなCSSだから、`body`に指定した`nowrap`を`header`など局所的にあてるように修正した。
